name: Run Spectral on Pull Requests

on:
  - pull_request

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: "openapi-v3.yaml"
          spectral_ruleset: ".spectral.json"
